### ISSUE TITLE
Auto-fill in information that is possible to predict

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-viewer#18]
Right now I spend hours manually registering meshes and rti objects even though there is a totally predictable naming and link scheme for these and this could be entered at any time even before we have the data. Would be good if this could be done automatically for all panels/surfaces straight into the database as soon as possible.

For instance each panel/surface will have 
a) one mesh object
b) two rti-objects

The link for the mesh object is: 
https://data.dh.gu.se/saintsophia/mesh/[panel-number].nxz

the links for the rti-objects are: 
https://data.dh.gu.se/saintsophia/rti/[panel-number]-set1/
and 
https://data.dh.gu.se/saintsophia/rti/[panel-number]-set2/

The title for the RTI sets are Set 1 and Set 2.

The only remanning field then would be number of triangles for the mesh-objects that I would enter manually.

**Comment by mtomasini** [comment]
I will do a batch upload this or next week.
