### ISSUE TITLE
Store point cloud annotations.json file in project folder rather than in module

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-viewer#19]
To keep it clean and each module general, the annotations.json file with project specific point cloud annotations should be kept in the projects folder instead.

**Comment by jonathanwestin** [comment]
As far as I can see the, the annotations.json file still resides in the point cloud-folder rather than in the project folder....

**Comment by jonathanwestin** [comment]
<img width="823" alt="Skärmavbild 2024-07-30 kl  10 40 29" src="https://github.com/user-attachments/assets/685aa880-9a16-45b8-942d-95761d851797">

**Comment by TristanBridge** [comment]
I will fix this. I misread the issue and moved the annotations for the iiif viewer. I guess that needed to be done anyways.
