### ISSUE TITLE
A show / hide annotations switcher for the IIIF-view

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-viewer#20]
Preferably the annotations would be hidden at start and the button would appear only if there are any annotations available. Center the button under the module-switcher.

<img width="861" alt="Skärmavbild 2024-07-01 kl  17 06 05" src="https://github.com/gu-gridh/multimodal-viewer/assets/70022179/2add9516-6583-47a5-a658-158a94f76428">

**Comment by TristanBridge** [comment]
Added the button, will position it and look into auto hiding annotations next.
