### ISSUE TITLE
Sophia backend needs a "Description" view (with the same options as the translations view)

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-viewer#26]
i.e it needs a free text field, a possibility to pick what language the description is in (mainly English and Ukrainian I would guess, but there might also be German and Spanish and French in the future), and possibility to add one or more authors/contributors to that description. 

Also, to be a functional view, the search function for Translations and Descriptions should be used to find what particular inscription they are connected to. Right now the search bar seems to be looking for something else. Once we have thousands of inscriptions we will potentially have several thousand descriptions in various languages, so being able to filter these by a particular inscription is a must.

**Comment by mtomasini** [comment]
Added description and added search functionalities on Translations and Descriptions.
