### ISSUE TITLE
Scrap the transcription view and add that as a free form field straight to the inscription object

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-viewer#27]
Since there will be only one transcription per inscription, and this is a field that we want everyone that register an inscription to fill out, I think it makes sense to have it tightly connected to and readily available straight in the inscription object rather than as a separate object that needs to be connected.

Naturally this would also be preferable for translations and descriptions, but that is perhaps impossible due to the fact that there will be multiple different languages for these?

also, make the authors list a multioption widget so several persons can be listed as contributors.

**Comment by mtomasini** [comment]
Merged transcriptions field into Inscription model. I also made authors multichoice.
